import { Prisma, Role } from '@prisma/client';
import prisma from '../config/database';
import { BadRequestError, NotFoundError } from '../errors/AppError';

const userSelect = { id: true, firstName: true, lastName: true, username: true, email: true, role: true, isActive: true, isEmailVerified: true, createdAt: true, updatedAt: true, _count: { select: { trips: true, communityPosts: true } } } as const;
const dayStart = (date: Date) => { const value = new Date(date); value.setUTCHours(0, 0, 0, 0); return value; };
const statusWhere = (today: Date) => ({ upcoming: { startDate: { gt: today } }, ongoing: { startDate: { lte: today }, endDate: { gte: today } }, completed: { endDate: { lt: today } } });

export async function listUsers(query: any) { const { search, role, isActive, page, limit } = query; const where: Prisma.UserWhereInput = { role: role as Role | undefined, isActive, ...(search ? { OR: [{ firstName: { contains: search, mode: 'insensitive' } }, { lastName: { contains: search, mode: 'insensitive' } }, { username: { contains: search, mode: 'insensitive' } }, { email: { contains: search, mode: 'insensitive' } }] } : {}) }; const [total, users] = await prisma.$transaction([prisma.user.count({ where }), prisma.user.findMany({ where, orderBy: { createdAt: 'desc' }, skip: (page - 1) * limit, take: limit, select: userSelect })]); return { items: users, meta: { page, limit, total, totalPages: Math.ceil(total / limit) } }; }
export async function getUser(userId: number) { const user = await prisma.user.findUnique({ where: { id: userId }, select: userSelect }); if (!user) throw new NotFoundError(`User with ID ${userId} not found`); return user; }
export async function setUserStatus(adminId: number, userId: number, isActive: boolean) { if (adminId === userId && !isActive) throw new BadRequestError('You cannot deactivate your own admin account'); await getUser(userId); return prisma.user.update({ where: { id: userId }, data: { isActive }, select: userSelect }); }
export async function stats() { const today = dayStart(new Date()); const ranges = statusWhere(today); const [totalUsers, totalTrips, completed, upcoming, ongoing, totalCities, totalActivities, totalCommunityPosts] = await Promise.all([prisma.user.count(), prisma.trip.count(), prisma.trip.count({ where: ranges.completed }), prisma.trip.count({ where: ranges.upcoming }), prisma.trip.count({ where: ranges.ongoing }), prisma.city.count(), prisma.activity.count(), prisma.communityPost.count()]); return { totalUsers, totalTrips, totalCompletedTrips: completed, totalUpcomingTrips: upcoming, totalOngoingTrips: ongoing, totalCities, totalActivities, totalCommunityPosts }; }
export async function popularCities(limit = 10) { const rows = await prisma.tripStop.groupBy({ by: ['cityId'], _count: { cityId: true }, orderBy: { _count: { cityId: 'desc' } }, take: limit }); const cities = await prisma.city.findMany({ where: { id: { in: rows.map((row) => row.cityId) } }, include: { country: true } }); return rows.map((row) => ({ city: cities.find((city) => city.id === row.cityId), tripStopCount: row._count.cityId })); }
export async function popularActivities(limit = 10) { const rows = await prisma.tripActivity.groupBy({ by: ['activityId'], _count: { activityId: true }, orderBy: { _count: { activityId: 'desc' } }, take: limit }); const activities = await prisma.activity.findMany({ where: { id: { in: rows.map((row) => row.activityId) } }, include: { city: true } }); return rows.map((row) => ({ activity: activities.find((activity) => activity.id === row.activityId), scheduledCount: row._count.activityId })); }
export async function engagement() { const [totalUsers, activeUsers, usersWithTrips, usersWithPosts, totalTrips] = await Promise.all([prisma.user.count(), prisma.user.count({ where: { isActive: true } }), prisma.user.count({ where: { trips: { some: {} } } }), prisma.user.count({ where: { communityPosts: { some: {} } } }), prisma.trip.count()]); return { totalUsers, activeUsers, usersWithTrips, usersWithCommunityPosts: usersWithPosts, tripsPerUser: totalUsers ? Number((totalTrips / totalUsers).toFixed(2)) : 0 }; }
export async function trends() { const [trips, users] = await Promise.all([prisma.$queryRaw<Array<{ period: Date; count: bigint }>>`SELECT DATE_TRUNC('month', created_at) AS period, COUNT(*)::bigint AS count FROM trips GROUP BY 1 ORDER BY 1`, prisma.$queryRaw<Array<{ period: Date; count: bigint }>>`SELECT DATE_TRUNC('month', created_at) AS period, COUNT(*)::bigint AS count FROM users GROUP BY 1 ORDER BY 1`]); return { trips: trips.map((row) => ({ period: row.period, count: Number(row.count) })), users: users.map((row) => ({ period: row.period, count: Number(row.count) })) }; }
