import { ExpenseCategory, Prisma, Visibility } from '@prisma/client';
import { randomBytes } from 'crypto';
import prisma from '../config/database';
import { BadRequestError, ConflictError, ForbiddenError, NotFoundError } from '../errors/AppError';

const dateOnly = (value: string | Date) => { const date = new Date(value); date.setUTCHours(0, 0, 0, 0); return date; };
const daysBetween = (start: Date, end: Date) => Math.floor((end.getTime() - start.getTime()) / 86400000) + 1;
const inRange = (date: Date, start: Date, end: Date) => date >= start && date <= end;
const publicTripInclude = { stops: { orderBy: { order: 'asc' as const }, select: { city: { select: { id: true, name: true, region: true, image: true, country: { select: { id: true, name: true, code: true } } } }, startDate: true, endDate: true, order: true } }, days: { orderBy: { date: 'asc' as const }, select: { date: true, title: true, activities: { orderBy: [{ sequence: 'asc' as const }], select: { id: true, startTime: true, endTime: true, customCost: true, sequence: true, activity: { select: { id: true, name: true, description: true, type: true, estimatedCost: true, durationMinutes: true, image: true, city: { select: { id: true, name: true } } } } } } } } };

async function ownedTrip(userId: number, tripId: number) {
  const trip = await prisma.trip.findUnique({ where: { id: tripId } });
  if (!trip) throw new NotFoundError(`Trip with ID ${tripId} not found`);
  if (trip.userId !== userId) throw new ForbiddenError('You do not have access to this trip');
  return trip;
}
async function ownedExpense(userId: number, tripId: number, expenseId: number) {
  await ownedTrip(userId, tripId);
  const expense = await prisma.tripExpense.findFirst({ where: { id: expenseId, tripId } });
  if (!expense) throw new NotFoundError(`Expense with ID ${expenseId} not found`);
  return expense;
}
function validateDate(date: Date, trip: any) { if (!inRange(date, trip.startDate, trip.endDate)) throw new BadRequestError('Expense date must fall within the trip date range'); }

export async function setBudget(userId: number, tripId: number, input: any) { await ownedTrip(userId, tripId); return prisma.trip.update({ where: { id: tripId }, data: { budgetAmount: input.amount, budgetCurrency: input.currency.toUpperCase() } }); }
export async function createExpense(userId: number, tripId: number, input: any) {
  const trip = await ownedTrip(userId, tripId); const date = dateOnly(input.date); validateDate(date, trip);
  if (input.tripStopId && !(await prisma.tripStop.findFirst({ where: { id: input.tripStopId, tripId } }))) throw new BadRequestError('Referenced stop does not belong to this trip');
  if (input.tripActivityId) { const item = await prisma.tripActivity.findUnique({ where: { id: input.tripActivityId }, include: { tripDay: true } }); if (!item || item.tripDay.tripId !== tripId) throw new BadRequestError('Referenced activity does not belong to this trip'); }
  return prisma.tripExpense.create({ data: { ...input, tripId, category: input.category as ExpenseCategory, currency: input.currency.toUpperCase(), date } });
}
export async function listExpenses(userId: number, tripId: number, filters: any) { await ownedTrip(userId, tripId); return prisma.tripExpense.findMany({ where: { tripId, category: filters.category, date: filters.date ? dateOnly(filters.date) : undefined }, orderBy: { date: 'asc' } }); }
export async function getExpense(userId: number, tripId: number, expenseId: number) { return ownedExpense(userId, tripId, expenseId); }
export async function updateExpense(userId: number, tripId: number, expenseId: number, input: any) { const trip = await ownedTrip(userId, tripId); await ownedExpense(userId, tripId, expenseId); const date = input.date ? dateOnly(input.date) : undefined; if (date) validateDate(date, trip); if (input.tripStopId && !(await prisma.tripStop.findFirst({ where: { id: input.tripStopId, tripId } }))) throw new BadRequestError('Referenced stop does not belong to this trip'); if (input.tripActivityId) { const item = await prisma.tripActivity.findUnique({ where: { id: input.tripActivityId }, include: { tripDay: true } }); if (!item || item.tripDay.tripId !== tripId) throw new BadRequestError('Referenced activity does not belong to this trip'); } return prisma.tripExpense.update({ where: { id: expenseId }, data: { ...input, date, category: input.category as ExpenseCategory | undefined, currency: input.currency?.toUpperCase() } }); }
export async function deleteExpense(userId: number, tripId: number, expenseId: number) { await ownedExpense(userId, tripId, expenseId); await prisma.tripExpense.delete({ where: { id: expenseId } }); }

async function expenseTotals(tripId: number) { const [aggregate, grouped] = await Promise.all([prisma.tripExpense.aggregate({ where: { tripId }, _sum: { amount: true } }), prisma.tripExpense.groupBy({ by: ['category'], where: { tripId }, _sum: { amount: true } })]); const categories: Record<string, number> = { TRANSPORT: 0, STAY: 0, ACTIVITY: 0, MEAL: 0, OTHER: 0 }; for (const row of grouped) categories[row.category] = row._sum.amount ?? 0; return { total: aggregate._sum.amount ?? 0, categories }; }
export async function budget(userId: number, tripId: number) { const trip = await ownedTrip(userId, tripId); const totals = await expenseTotals(tripId); const amount = trip.budgetAmount ?? 0; const tripDays = daysBetween(trip.startDate, trip.endDate); return { budget: { amount, currency: trip.budgetCurrency }, summary: { totalSpent: totals.total, remaining: amount - totals.total, percentageUsed: amount ? Number(((totals.total / amount) * 100).toFixed(2)) : 0 }, categoryBreakdown: totals.categories, dailyAverage: Number((totals.total / tripDays).toFixed(2)), overBudget: amount > 0 && totals.total > amount }; }
export async function dailyBudget(userId: number, tripId: number) { const trip = await ownedTrip(userId, tripId); const daily = trip.budgetAmount ? trip.budgetAmount / daysBetween(trip.startDate, trip.endDate) : 0; const rows = await prisma.tripExpense.groupBy({ by: ['date'], where: { tripId }, _sum: { amount: true }, orderBy: { date: 'asc' } }); return rows.map((row) => { const totalSpent = row._sum.amount ?? 0; return { date: dayValue(row.date), totalSpent, budget: Number(daily.toFixed(2)), remaining: Number((daily - totalSpent).toFixed(2)), isOverBudget: daily > 0 && totalSpent > daily }; }); }
function dayValue(value: Date) { return value.toISOString().slice(0, 10); }
export async function updateBudget(userId: number, tripId: number, input: any) { return setBudget(userId, tripId, input); }
export async function calendar(userId: number, tripId: number) { await ownedTrip(userId, tripId); const days = await prisma.tripDay.findMany({ where: { tripId }, orderBy: { date: 'asc' }, include: { activities: { orderBy: { sequence: 'asc' }, include: { activity: { include: { city: true } } } } } }); return days.reduce((result: Record<string, unknown[]>, day: any) => { result[dayValue(day.date)] = day.activities.map((item: any) => ({ id: item.id, tripDayId: day.id, date: dayValue(day.date), startTime: item.startTime, endTime: item.endTime, cost: item.customCost ?? item.activity.estimatedCost, activity: item.activity })); return result; }, {}); }

export async function dashboard(userId: number) { const trips = await prisma.trip.findMany({ where: { userId }, orderBy: { updatedAt: 'desc' }, take: 20, include: { _count: { select: { stops: true } }, expenses: true } }); const today = dateOnly(new Date()); const classify = (trip: any) => today < trip.startDate ? 'upcoming' : today > trip.endDate ? 'completed' : 'ongoing'; const mapped = trips.map((trip: any) => ({ id: trip.id, name: trip.name, startDate: trip.startDate, endDate: trip.endDate, coverPhoto: trip.coverPhoto, status: classify(trip), destinationCount: trip._count.stops })); const popular = await prisma.city.findMany({ orderBy: { popularityScore: 'desc' }, take: 6, include: { country: true } }); const budgetHighlights = trips.filter((trip: any) => trip.budgetAmount !== null).map((trip: any) => { const spent = trip.expenses.reduce((total: number, expense: any) => total + expense.amount, 0); return { tripId: trip.id, tripName: trip.name, budget: trip.budgetAmount, currency: trip.budgetCurrency, spent, remaining: trip.budgetAmount - spent, percentageUsed: trip.budgetAmount ? Number(((spent / trip.budgetAmount) * 100).toFixed(2)) : 0 }; }); return { trips: { recent: mapped.slice(0, 5), upcoming: mapped.filter((trip) => trip.status === 'upcoming'), ongoing: mapped.filter((trip) => trip.status === 'ongoing'), completed: mapped.filter((trip) => trip.status === 'completed') }, destinations: { popular, recommended: popular }, budgetHighlights }; }

export async function saveDestination(userId: number, cityId: number) { const city = await prisma.city.findUnique({ where: { id: cityId }, include: { country: true } }); if (!city) throw new NotFoundError(`City with ID ${cityId} not found`); const existing = await prisma.savedDestination.findUnique({ where: { userId_cityId: { userId, cityId } } }); if (existing) throw new ConflictError('Destination is already saved'); return prisma.savedDestination.create({ data: { userId, cityId }, include: { city: { include: { country: true } } } }); }
export async function listSavedDestinations(userId: number) { return prisma.savedDestination.findMany({ where: { userId }, orderBy: { createdAt: 'desc' }, include: { city: { include: { country: true } } } }); }
export async function deleteSavedDestination(userId: number, cityId: number) { const saved = await prisma.savedDestination.findUnique({ where: { userId_cityId: { userId, cityId } } }); if (!saved) throw new NotFoundError('Saved destination not found'); await prisma.savedDestination.delete({ where: { id: saved.id } }); }

export async function shareTrip(userId: number, tripId: number, frontendUrl: string) { await ownedTrip(userId, tripId); const slug = randomBytes(18).toString('base64url'); const share = await prisma.tripShare.upsert({ where: { tripId }, update: {}, create: { tripId, shareSlug: slug } }); await prisma.trip.update({ where: { id: tripId }, data: { visibility: Visibility.PUBLIC } }); return { shareSlug: share.shareSlug, visibility: Visibility.PUBLIC, url: `${frontendUrl.replace(/\/$/, '')}/public/trips/${share.shareSlug}` }; }
export async function disableShare(userId: number, tripId: number) { await ownedTrip(userId, tripId); await prisma.tripShare.deleteMany({ where: { tripId } }); await prisma.trip.update({ where: { id: tripId }, data: { visibility: Visibility.PRIVATE } }); }
export async function publicTrip(shareSlug: string) { const share = await prisma.tripShare.findUnique({ where: { shareSlug }, include: { trip: { include: publicTripInclude } } }); if (!share || share.trip.visibility !== Visibility.PUBLIC) throw new NotFoundError('Public trip is not available'); const { trip } = share; return { id: trip.id, name: trip.name, description: trip.description, coverPhoto: trip.coverPhoto, startDate: trip.startDate, endDate: trip.endDate, stops: trip.stops, days: trip.days }; }
export async function copyTrip(userId: number, shareSlug: string) { const source = await publicTrip(shareSlug); return prisma.$transaction(async (tx) => { const trip = await tx.trip.findUnique({ where: { id: source.id }, include: { stops: true, days: { include: { activities: true } } } }); if (!trip || trip.visibility !== Visibility.PUBLIC) throw new NotFoundError('Public trip is not available'); const cloned = await tx.trip.create({ data: { userId, name: `${trip.name} (Copy)`, description: trip.description, coverPhoto: trip.coverPhoto, startDate: trip.startDate, endDate: trip.endDate, visibility: Visibility.PRIVATE, budgetAmount: trip.budgetAmount, budgetCurrency: trip.budgetCurrency } }); for (const stop of trip.stops) await tx.tripStop.create({ data: { tripId: cloned.id, cityId: stop.cityId, startDate: stop.startDate, endDate: stop.endDate, order: stop.order, notes: stop.notes } }); for (const day of trip.days) { const newDay = await tx.tripDay.create({ data: { tripId: cloned.id, date: day.date, title: day.title, notes: day.notes } }); for (const activity of day.activities) await tx.tripActivity.create({ data: { tripDayId: newDay.id, activityId: activity.activityId, startTime: activity.startTime, endTime: activity.endTime, customCost: activity.customCost, notes: activity.notes, sequence: activity.sequence } }); } return cloned; }); }
