import { Prisma, Visibility } from '@prisma/client';
import prisma from '../config/database';
import { BadRequestError, ConflictError, ForbiddenError, NotFoundError } from '../errors/AppError';

const tripInclude = { stops: { orderBy: { order: 'asc' as const }, include: { city: { include: { country: true } } } }, days: { orderBy: { date: 'asc' as const }, include: { activities: { orderBy: { sequence: 'asc' as const }, include: { activity: { include: { city: true } } } } } } };
const asDate = (value: string | Date) => { const date = new Date(value); date.setUTCHours(0, 0, 0, 0); return date; };
const dayValue = (value: Date) => value.toISOString().slice(0, 10);
const inRange = (date: Date, start: Date, end: Date) => date >= start && date <= end;
const rangeValid = (start: Date, end: Date) => start <= end;

async function ownedTrip(userId: number, tripId: number) {
  const trip = await prisma.trip.findUnique({ where: { id: tripId } });
  if (!trip) throw new NotFoundError(`Trip with ID ${tripId} not found`);
  if (trip.userId !== userId) throw new ForbiddenError('You do not have access to this trip');
  return trip;
}
function status(start: Date, end: Date) { const today = asDate(new Date()); return today < start ? 'UPCOMING' : today > end ? 'COMPLETED' : 'ONGOING'; }
function serializeTrip(trip: any) { return { ...trip, status: status(trip.startDate, trip.endDate), destinationCount: trip._count?.stops ?? trip.stops?.length ?? 0 }; }
function ensureRange(start: Date, end: Date, trip: any) { if (!rangeValid(start, end)) throw new BadRequestError('End date cannot be before start date'); if (!inRange(start, trip.startDate, trip.endDate) || !inRange(end, trip.startDate, trip.endDate)) throw new BadRequestError('Dates must fall within the trip date range'); }

export async function createTrip(userId: number, input: any) { const startDate = asDate(input.startDate); const endDate = asDate(input.endDate); if (!rangeValid(startDate, endDate)) throw new BadRequestError('End date cannot be before start date'); return prisma.trip.create({ data: { ...input, userId, startDate, endDate, visibility: input.visibility as Visibility | undefined } }); }
export async function listTrips(userId: number, filter?: string) { const trips = await prisma.trip.findMany({ where: { userId }, orderBy: { startDate: 'asc' }, include: { _count: { select: { stops: true } } } }); return trips.filter((trip) => !filter || status(trip.startDate, trip.endDate) === filter).map(serializeTrip); }
export async function getTrip(userId: number, tripId: number) { return serializeTrip(await prisma.trip.findFirst({ where: { id: tripId, userId }, include: { _count: { select: { stops: true } }, stops: { orderBy: { order: 'asc' }, include: { city: true } } } } ).then((trip) => { if (!trip) throw new NotFoundError(`Trip with ID ${tripId} not found`); return trip; })); }
export async function updateTrip(userId: number, tripId: number, input: any) { const trip = await ownedTrip(userId, tripId); const startDate = input.startDate ? asDate(input.startDate) : trip.startDate; const endDate = input.endDate ? asDate(input.endDate) : trip.endDate; if (!rangeValid(startDate, endDate)) throw new BadRequestError('End date cannot be before start date'); const stops = await prisma.tripStop.findMany({ where: { tripId } }); for (const stop of stops) ensureRange(stop.startDate, stop.endDate, { ...trip, startDate, endDate }); const days = await prisma.tripDay.findMany({ where: { tripId } }); if (days.some((day) => !inRange(day.date, startDate, endDate))) throw new BadRequestError('New trip dates would invalidate itinerary days'); return prisma.trip.update({ where: { id: tripId }, data: { ...input, startDate, endDate } }); }
export async function deleteTrip(userId: number, tripId: number) { await ownedTrip(userId, tripId); await prisma.trip.delete({ where: { id: tripId } }); }

async function ownedStop(userId: number, tripId: number, stopId: number) { const trip = await ownedTrip(userId, tripId); const stop = await prisma.tripStop.findFirst({ where: { id: stopId, tripId }, include: { city: true } }); if (!stop) throw new NotFoundError(`Stop with ID ${stopId} not found`); return { trip, stop }; }
async function ensureNoOverlap(tripId: number, start: Date, end: Date, exclude?: number) { const overlap = await prisma.tripStop.findFirst({ where: { tripId, id: exclude ? { not: exclude } : undefined, startDate: { lte: end }, endDate: { gte: start } } }); if (overlap) throw new ConflictError('Stop dates overlap an existing stop'); }
export async function createStop(userId: number, tripId: number, input: any) { const trip = await ownedTrip(userId, tripId); const city = await prisma.city.findUnique({ where: { id: input.cityId } }); if (!city) throw new NotFoundError(`City with ID ${input.cityId} not found`); const startDate = asDate(input.startDate); const endDate = asDate(input.endDate); ensureRange(startDate, endDate, trip); await ensureNoOverlap(tripId, startDate, endDate); const last = await prisma.tripStop.findFirst({ where: { tripId }, orderBy: { order: 'desc' } }); return prisma.tripStop.create({ data: { ...input, tripId, startDate, endDate, order: (last?.order ?? 0) + 1 } }); }
export async function listStops(userId: number, tripId: number) { await ownedTrip(userId, tripId); return prisma.tripStop.findMany({ where: { tripId }, orderBy: { order: 'asc' }, include: { city: { include: { country: true } } } }); }
export async function getStop(userId: number, tripId: number, stopId: number) { return (await ownedStop(userId, tripId, stopId)).stop; }
export async function updateStop(userId: number, tripId: number, stopId: number, input: any) { const { trip, stop } = await ownedStop(userId, tripId, stopId); const startDate = input.startDate ? asDate(input.startDate) : stop.startDate; const endDate = input.endDate ? asDate(input.endDate) : stop.endDate; ensureRange(startDate, endDate, trip); await ensureNoOverlap(tripId, startDate, endDate, stopId); if (input.cityId && !(await prisma.city.findUnique({ where: { id: input.cityId } }))) throw new NotFoundError(`City with ID ${input.cityId} not found`); return prisma.tripStop.update({ where: { id: stopId }, data: { ...input, startDate, endDate } }); }
export async function deleteStop(userId: number, tripId: number, stopId: number) { await ownedStop(userId, tripId, stopId); await prisma.tripStop.delete({ where: { id: stopId } }); const remaining = await prisma.tripStop.findMany({ where: { tripId }, orderBy: { order: 'asc' } }); await prisma.$transaction(remaining.map((item, index) => prisma.tripStop.update({ where: { id: item.id }, data: { order: index + 1 } }))); }
export async function reorderStops(userId: number, tripId: number, stopIds: number[]) { await ownedTrip(userId, tripId); const stops = await prisma.tripStop.findMany({ where: { tripId }, select: { id: true } }); if (stops.length !== stopIds.length || stops.some((stop) => !stopIds.includes(stop.id))) throw new BadRequestError('stopIds must contain every stop in this trip exactly once'); await prisma.$transaction([...stopIds.map((id, index) => prisma.tripStop.update({ where: { id }, data: { order: -(index + 1) } })), ...stopIds.map((id, index) => prisma.tripStop.update({ where: { id }, data: { order: index + 1 } }))]); }

async function ownedDay(userId: number, tripId: number, dayId: number) { const trip = await ownedTrip(userId, tripId); const day = await prisma.tripDay.findFirst({ where: { id: dayId, tripId }, include: { activities: { orderBy: { sequence: 'asc' }, include: { activity: { include: { city: true } } } } } }); if (!day) throw new NotFoundError(`Itinerary day with ID ${dayId} not found`); return { trip, day }; }
export async function createDay(userId: number, tripId: number, input: any) { const trip = await ownedTrip(userId, tripId); const date = asDate(input.date); if (!inRange(date, trip.startDate, trip.endDate)) throw new BadRequestError('Day date must fall within the trip date range'); return prisma.tripDay.create({ data: { ...input, tripId, date } }); }
export async function listDays(userId: number, tripId: number) { await ownedTrip(userId, tripId); return prisma.tripDay.findMany({ where: { tripId }, orderBy: { date: 'asc' }, include: { activities: { orderBy: { sequence: 'asc' }, include: { activity: { include: { city: true } } } } } }); }
export async function getDay(userId: number, tripId: number, dayId: number) { return (await ownedDay(userId, tripId, dayId)).day; }
export async function updateDay(userId: number, tripId: number, dayId: number, input: any) { const { trip, day } = await ownedDay(userId, tripId, dayId); const date = input.date ? asDate(input.date) : day.date; if (!inRange(date, trip.startDate, trip.endDate)) throw new BadRequestError('Day date must fall within the trip date range'); return prisma.tripDay.update({ where: { id: dayId }, data: { ...input, date } }); }
export async function deleteDay(userId: number, tripId: number, dayId: number) { await ownedDay(userId, tripId, dayId); await prisma.tripDay.delete({ where: { id: dayId } }); }
export async function addActivity(userId: number, tripId: number, dayId: number, input: any) { const { trip, day } = await ownedDay(userId, tripId, dayId); const activity = await prisma.activity.findUnique({ where: { id: input.activityId } }); if (!activity) throw new NotFoundError(`Activity with ID ${input.activityId} not found`); const stop = await prisma.tripStop.findFirst({ where: { tripId, cityId: activity.cityId, startDate: { lte: day.date }, endDate: { gte: day.date } } }); if (!stop) throw new BadRequestError('Activity city must match a stop covering this itinerary day'); const last = await prisma.tripActivity.findFirst({ where: { tripDayId: dayId }, orderBy: { sequence: 'desc' } }); return prisma.tripActivity.create({ data: { ...input, tripDayId: dayId, sequence: (last?.sequence ?? 0) + 1 } }); }
export async function updateActivity(userId: number, id: number, input: any) { const item = await prisma.tripActivity.findUnique({ where: { id }, include: { tripDay: true } }); if (!item) throw new NotFoundError(`Trip activity with ID ${id} not found`); await ownedTrip(userId, item.tripDay.tripId); return prisma.tripActivity.update({ where: { id }, data: input }); }
export async function deleteActivity(userId: number, id: number) { const item = await prisma.tripActivity.findUnique({ where: { id }, include: { tripDay: true } }); if (!item) throw new NotFoundError(`Trip activity with ID ${id} not found`); await ownedTrip(userId, item.tripDay.tripId); await prisma.tripActivity.delete({ where: { id } }); }
export async function reorderActivities(userId: number, tripDayId: number, activityIds: number[]) { const day = await prisma.tripDay.findUnique({ where: { id: tripDayId }, include: { activities: { select: { id: true } } } }); if (!day) throw new NotFoundError(`Itinerary day with ID ${tripDayId} not found`); await ownedTrip(userId, day.tripId); if (day.activities.length !== activityIds.length || day.activities.some((item) => !activityIds.includes(item.id))) throw new BadRequestError('activityIds must contain every activity in this day exactly once'); await prisma.$transaction([...activityIds.map((id, index) => prisma.tripActivity.update({ where: { id }, data: { sequence: -(index + 1) } })), ...activityIds.map((id, index) => prisma.tripActivity.update({ where: { id }, data: { sequence: index + 1 } }))]); }
export async function itinerary(userId: number, tripId: number) { await ownedTrip(userId, tripId); const trip = await prisma.trip.findFirst({ where: { id: tripId, userId }, include: tripInclude }); if (!trip) throw new NotFoundError(`Trip with ID ${tripId} not found`); return { trip: serializeTrip(trip), stops: trip.stops, days: trip.days }; }
